spring.application.name=workflow

# Server
server.port=8081

# DB (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/workflowdb
spring.datasource.username=workflow
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Seoul

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.highlight_sql=true
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.orm.jdbc.bind=trace

# JWT Option
# JWT \uC11C\uBA85(Signature) \uC744 \uB9CC\uB4E4 \uB54C \uC4F0\uB294 \uB300\uCE6D\uD0A4
# \uC11C\uBC84\uB9CC \uC54C\uACE0 \uC788\uC5B4\uC57C \uD568.
# \uD1A0\uD070 \uBC1C\uAE09 \uC2DC \uC11C\uBA85, \uC694\uCCAD \uC2DC \uD1A0\uD070 \uAC80\uC99D
jwt.secret=Z9x1Q2w3E4r5T6y7U8i9O0pAaBbCcDdEeFfGgHhIiJjKkLl
# \uC561\uC138\uC2A4 \uD1A0\uD070 \uC720\uD6A8 \uC2DC\uAC04
jwt.access-exp-min=15
# \uB9AC\uD504\uB798\uC2DC \uD1A0\uD070 \uC720\uB8CC \uAE30\uAC04
jwt.refresh-exp-day=14
logging.level.org.springframework.security=DEBUG

# HMAC-SHA256
hasher.secret = "REFRESH_TOKEN_SECRET_KEY"

# revoked refresh token \uC815\uB9AC \uBC30\uCE58 (\uAE30\uBCF8 \uBE44\uD65C\uC131)
# \uB098\uC911\uC5D0 \uBC30\uD3EC\uD560\uB54C true\uB85C \uBC14\uAFB8\uAE30
app.token-cleanup.enabled=true
app.token-cleanup.days=14

# \uC11C\uBC84\uC6A9 \uC5C5\uB85C\uB4DC \uACBD\uB85C
app.upload-dir=/home/ubuntu/WorkFlow-img/uploads
app.upload-tmp-ttl-hours=24

# \uD30C\uC77C 1\uAC1C \uCD5C\uB300 \uD06C\uAE30
spring.servlet.multipart.max-file-size=20MB

# \uC694\uCCAD \uC804\uCCB4 \uCD5C\uB300 \uD06C\uAE30
spring.servlet.multipart.max-request-size=100MB

# \uC0AD\uC81C\uB41C \uCCA8\uBD80\uD30C\uC77C \uC2E4\uC81C \uC815\uB9AC \uBC30\uCE58
app.attachment-cleanup.enabled=true
# \uC785\uB825\uD55C \uAE30\uAC04 \uC9C0\uB09C \uAC83\uB4E4\uC744 \uC0AD\uC81C
app.attachment-cleanup.retention-days=14
#app.attachment-cleanup.retention-minutes=30

# Task \uC774\uBBF8\uC9C0/\uD3F4\uB354 \uC790\uB3D9 \uC0AD\uC81C \uBCF4\uC874 \uAE30\uAC04 (\uC77C \uB2E8\uC704)
app.task-cleanup.retention-days=14